### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jgillich**
Needed serde 0.7, and thought I would update a few other things as well while I'm at it.

### CODE REVIEW

**Comment by jgillich** [comment]
Note that I've only build-tested this, so you probably want to try if it actually works.

**Comment by cmbrandenburg** [comment]
Thanks, Jakob! This is great!

This is as good a time as any to announce that I have a new crate in the works, [Chill](https://github.com/chill-rs/chill), that will replace the `couchdb` crate. You can read about why I'm doing this [here](https://cmbrandenburg.github.io/post/2016-02-23-rethinking_couchdb_in_rust/). The gist is that Chill provides a higher and more useful abstraction than `couchdb`.

My goal is to release Chill 0.1.0 this weekend. However, this is a “get it out there” release; it will take a few months before Chill catches up and wholly surpasses `couchdb` in CouchDB API coverage.

**Comment by jgillich** [comment]
Sounds great! Since Chili is the way forward, I'll probably switch soon and contribute a few things along the way.

**Comment by cmbrandenburg** [comment]
OK, we're in business with [Chill](https://crates.io/crates/chill), v0.1.0. Please feel free to help out in any way!

**Pull request merged**
